# -*- coding: utf-8 -*-
"""LinearRegr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11KyfPsh37t0D5-d0grI7L6VrvfxU9QqJ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm

df=pd.read_csv("Boston.csv", index_col=0)
corr = np.zeros(df.shape[1])  # Creates an array with one slot per column

for i in range(0,14):
  if i==4:
    continue
  corr[i] = np.corrcoef(df.nox,df.iloc[:,i])[0,1]

for k in range(0,14):
  print(corr[k])

mod_arr = np.abs(corr)  # modulus = absolute value
max_val = mod_arr.max()

print("Max corrcoef =", max_val)
max_index = np.argmax(mod_arr)  # index of max value
print("Index = ", max_index)


col_name = df.columns[max_index]
print("The best predictor of NOX is", col_name)

y = df.nox
X = df.iloc[:,max_index]
X = sm.add_constant(X)

lr_model = sm.OLS(y,X).fit()

print(lr_model.params)
print(lr_model.summary())